### ISSUE TITLE
conformance: Should an unbound variable be error or unknown at runtime?

### ISSUE THREAD

**Issue by gabrielsz** [cel-expr/cel-go#154]
**Describe the bug**
For a simple expression "x" (representing an unbound variable), the type checker will correctly report an error:
```
"undeclared reference to 'x' (in container '')"
```

But if you're not using the type checker, the expression will yield an `unknown` value as the result. This issue exists to make a decision on whether to specify the behavior in the spec, or to change the behavior in cel-go

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
x
```

Test setup:
```cel-spec
  test {
    name: "self_eval_unbound_lookup"
    expr: "x"
    disable_check: true
    ## Expected behavior
    eval_error: {
      errors: { message: "undeclared reference to 'x' (in container '')" }
    }
    ## Current behavior as expressed by the cel-go implementation
    #unknown: {
    #  exprs: 1
    #}
  }
```

**Expected behavior**
I was originally expecting the same error message in the interpreter than the one I got from the checker

**Comment by JimLarson** [comment]
Note that if you'd like an "unknown" result, you can get it by binding the inputs to "unknown".  I claim we'd want to get an error instead of unknown when evaluating "myvra == 7" with the binding "myvar: unknown".  Furthermore, having unbound vars be errors lets us keep "unknowns" as a meta-semantics of the language, rather than having to specify rules for them.
