### ISSUE TITLE
Is it possible to translate AST to equivalent javascript?

### ISSUE THREAD

**Issue by huangjunwen** [cel-expr/cel-go#201]
Hi, I have a website written in python, now is moving to golang. I have implemented a sandbox in python (restrict byte code) for evaluating product price in server side, and a AST translator to convert python code to equivalent Javascript code for client side. 

As we are moving to go, lm looking for alternative solution in go. It seems that CEL is a good fit for this use case. But I’m new to CEL, I want to know is it possible to translate CEL AST to js? Or is there any CEL-javascript (I didn’t find) that can run CEL in js environment? Thank you

**Comment by TristonianJones** [comment]
Thanks for your interest! It is possible to translate most of CEL into valid JavaScript with a couple of exceptions:
1. Numeric and bytes types.
2. Comprehension Macros.
3. Commutative `&&`, `||`. 

CEL supports 64-bit numeric types, with support for both `int64` and `uint64`. If you need support for these values, then compatibility options to handle numbers in these ranges exist as extensions to JavaScript, e.g. [js-ctypes](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes) (which happens to be deprecated).

Often bytes types are not heavily used within JavaScript, but likewise if you need to use them, the canonical serialization from bytes to base64-encoded string or `Uint8Array` used for protobufs should be followed: https://developers.google.com/protocol-buffers/docs/reference/javascript-generated#bytes

The first two issues affect primitive representation and operations, but if you're not using bytes or uints and are only doing math within the `int53` range, then the only hurdles that remain would be to translate macros to closures and to wrap logical `&&`, `||` into functions that can handle errors on either side of the expression by using something like `try..catch`.

To date there hasn't been much effort in client-side JavaScript evaluators due to the limitations of the environment, but for some use-cases with a subset of the CEL features, a JavaScript implementation (or source to source translation) will work quite well.

**Comment by huangjunwen** [comment]
Thanks very much for your informative reply. I’ll do some research on it.

**Comment by TristonianJones** [comment]
You're welcome. Feel free to reach out at the cel-go-discuss@googlegroups.com if you have further questions.

**Comment by zhyon404** [comment]
@huangjunwen CEL AST.Expr is protobuf message, which can be trans to js by grpc call, This partially solved my problem.
