### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by antonmedv** [cel-expr/cel-go#224]
Hi,

Awesome project 😀 
But I found this in README.md:
> ... https://github.com/antonmedv/expr ...
> StartsWith(name, Concat("/groups/", group)) // Expr
> BenchmarkExpr-8          1000000              1402 ns/op

Please, update README.md with new results:
```
❯❯❯ go test -bench=startswith
goos: darwin
goarch: amd64
pkg: github.com/antonmedv/golang-expression-evaluation-comparison
Benchmark_celgo_startswith-8   	 3000000	       466 ns/op
Benchmark_expr_startswith-8    	 5000000	       362 ns/op
PASS
ok  	github.com/antonmedv/golang-expression-evaluation-comparison	4.081s
```

**Comment by TristonianJones** [comment]
Hi Anton,

Thanks for setting up a benchmark for various Go expression evaluation libraries. I have a couple of PRs in progress (#223, https://github.com/TristonianJones/cel-go/pull/1), but once they're in I'll happily run your benchmarks and update the `README.md`. Do you mind if I refer to your benchmark repo as part of the update? I think it's a helpful resource.

-Tristan

**Comment by TristonianJones** [comment]
I did notice that the optimization flag is currently off in the benchmark, but the name of the flag is changing. Once the PRs are merged, you might want to make the following change:

```
prg, err := env.Program(checked, cel.EvalOptions(cel.OptOptimize))
```

By default CEL doesn't optimize the expression plan since it's not clear whether the use case will iterate frequently over the same expression. I should make that option easier to find and use though. 

Here were the numbers from my local build, but there are still more changes in flight that should further improve the numbers. 

```
goos: linux
goarch: amd64
pkg: github.com/antonmedv/golang-expression-evaluation-comparison
Benchmark_bexpr-12               	 2000000	       794 ns/op
Benchmark_celgo-12               	 5000000	       276 ns/op
Benchmark_celgo_startswith-12    	 3000000	       594 ns/op
Benchmark_expr-12                	 5000000	       306 ns/op
Benchmark_expr_startswith-12     	 3000000	       562 ns/op
Benchmark_goja-12                	 5000000	       390 ns/op
Benchmark_govaluate-12           	 5000000	       358 ns/op
Benchmark_gval-12                	  100000	     13949 ns/op
Benchmark_otto-12                	 1000000	      1531 ns/op
```

If you implement a custom `interpreter.Activation` (which you might want to do if your input is always the same shape) you can drop the number even further:

```
Benchmark_celgo-12               	10000000	       224 ns/op
Benchmark_celgo_startswith-12    	 3000000	       537 ns/op
```

**Comment by antonmedv** [comment]
Ok, Awesome! What optimization this flag turns on?  I now will add this option, but let me know if new version are ready. 

Can you tell me what is an nactivation? What concept is it?

**Comment by TristonianJones** [comment]
Hi Anton, 

The v0.3.0 release will likely ship early next week. The pending PRs are somewhat complicated so they'll take some time to review. 

CEL started off with the aim of evaluating many different expressions against the same input, sometimes with partial state across environments. The `interpreter.Activation` is basically a glorified map with inheritance / scoping. However, when the same input is used with many expressions it can be used to speed up variable accesses from CEL to the input. 

Here's an example:

```go
type params struct {
  Origin interface{}
  Country interface{}
  Value interface{}
  Adults interface{}
}

func (p *params) Find(name string) (interface{}, bool) {
   switch name {
     case "Origin":
       return p.Origin
     case "Country":
       return p.Country
     case "Value":
       return p.Value
     case "Adults":
       return p.Adults
     default:
       return nil, false
   }
}

func (p *params) Parent() interpreter.Activation {
  return nil
}
```

The `switch` is a bit painful, but it does lead to faster accesses than the generic `map[string]interface{}`. The reason the fields are `interface{}` type is because Go will implicitly allocation an `interface{}` for primitive typed values because of the `Find` return type. This example means that you would pay the cost of the allocation either up-front or on demand, so depending on your use case (one expression, many inputs vs. one input, many expressions) you might want one format over another.

At any rate, if this technique helps with your project, so much the better. I expect it may not be as necessary since CEL has to negotiate several different type systems (proto, json, go) and when it doubt unifies to its own internal representation. When data is converted to a CEL value type there is usually a costly allocation; however, it typically ends up being a small price for cross-runtime compatibility between Go and C++.

**Comment by antonmedv** [comment]
Hi @TristonianJones,
How is your PR going? 
In expr bottleneck is always reflect package, as I'm trying to work with raw Go structures and methods. Avoiding using reflect speeds up execution dramatically. And I'm trying to find the balance between speed and simplicity of use.

**Comment by TristonianJones** [comment]
Hi Anton,

I just got back from vacation and started discussing the PR in depth with
Jim Larson mostly with an emphasis on simplifying the split between
indicating the presence of partial state and identifying parts of an
expression that might describe data accesses. It needs a thorough scrub.

The rule of thumb I used was to optimize for valid protobuf map key types
since this would also cover field selections (strings) and list indices
(int). The result was a big ugly switch statement representing a partial
set of the most commonly used types. Custom structs are notably absent. For
this case, I tried to make it easy to inspect the field and index
traversals on an object so a custom resolver could be written to index
directly into the field of arbitrary depth. It's still a work in progress
though and not super easy to use. And sometimes the code still needs to
reflect, like when it has to cross a function boundary.

Let me know if you want to chat more. Always fun to talk shop.

-Tristan

**Comment by antonmedv** [comment]
How are you dealing with unnecessary traversal of, for example, binary AND operation?

If I understand correctly CEL is parsing `&&` as left associative? 
```
echo 'a && b && c && d && e || f' | go run github.com/antonmedv/expr/cmd/exe -ast -dot | dot -Tpng
```
![left-recursive](https://user-images.githubusercontent.com/141232/60174870-b2550a00-981a-11e9-871d-2dc42fed65f2.png)

But in case if `a` is **false** there is no need to traverse tree backwards and the only `f` is needed to be evaluated.
 
Or is right associative? 
```
echo '(a && (b && (c && (d && e)))) || f' | go run github.com/antonmedv/expr/cmd/exe -ast -dot | dot -Tpng | term-img
```
![right-recursive](https://user-images.githubusercontent.com/141232/60175010-0b24a280-981b-11e9-90d7-421b0e61645a.png)

**Comment by TristonianJones** [comment]
I've removed the performance section from the `README.md`. You've done really great work on optimizing `expr` and it looks like a lot of the other libraries have also made improvements as well. Since I can't keep this up to date, I'm just going to remove it and let folks look at the benchmarks in `interpreter/interpreter_test.go` as a reference point instead. 

Thanks for giving me some good performance targets to shoot for in the coming weeks.
