### ISSUE TITLE
Panic during type checking phase in `pb.(*TypeDescription).getFieldsInfo`

### ISSUE THREAD

**Issue by tobiaszheller** [cel-expr/cel-go#230]
**Describe the bug**
Type checking expression on proto type concurrently is causing panic (concurrent map writes in `cel-go/common/types/pb.(*TypeDescription).getFieldsInfo`)

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [x]  checker
- [ ]  interpreter

Sample expression and input that reproduces the issue:
I have simple engine type which initialize env and provides ParseAndCheck function.
```go
type engine struct {
	env cel.Env
}

func New() (*engine, error) {
	e, err := cel.NewEnv(
		cel.Container("google.api.expr.v1alpha1"),
		cel.Types(&exprpb.Expr{}),
		cel.Declarations(
			decls.NewIdent("expr",
				decls.NewObjectType("google.api.expr.v1alpha1.Expr"), nil),
		),
	)
	if err != nil {
		return nil, err
	}
	return &engine{
		env: e,
	}, nil
}

func (e *engine) ParseAndCheck(expr string) (cel.Ast, error) {
	p, iss := e.env.Parse(expr)
	if iss != nil && iss.Err() != nil {
		return nil, iss.Err()
	}
	c, iss := e.env.Check(p)
	if iss != nil && iss.Err() != nil {
		return nil, iss.Err()
	}
	return c, nil
}
```
Test setup:
```go
func TestParseAndCheck(t *testing.T) {
	engine, err := New()
	if err != nil {
		t.Fatal(err)
	}
	const concurrency = 2
	wgDone := sync.WaitGroup{}
	wgDone.Add(concurrency)

	for i := 0; i < concurrency; i++ {
		go func() {
			defer wgDone.Done()
			expr := fmt.Sprintf("expr.id")
			_, errParse := engine.ParseAndCheck(expr)
			if errParse != nil {
				t.Fatalf("failed to process engine: %v", errParse)
			}
		}()
	}
	wgDone.Wait()
}

```
It can be also observed running above test case with `race` flag.

**Expected behavior**
Run without panic.

**Comment by krzysztofdrys** [comment]
Hi! I work in the same company as @nephe. First of all: thanks for making repo. So far we have enjoyed working with CEL, especially it's type-safety. 

Now, regarding our problem. We assumed that `cel.Env` is safe for concurrent usage. As far as I can see, nothing in the comments says it isn't. :) Bug described by @nephe caused a few panics on our production. I submitted a proposed fix. It might require some work, at very least a unit test. 

But before I invest more time into this PR, I would like to know, whether this is right direction? I mean, there is no point in adding tests (or my PR), if `cel.Env` is not expected to safe for the concurrent usage.

**Comment by TristonianJones** [comment]
Hi Krzysztof,

Thanks for the report. The expectation is that environments are thread safe. There was some prior work to isolate different type repositories from each other via `pb.Db`, but it's likely that the lazily computed field information was overlooked as part of that effort since a race between the writes will result in the same value recorded in the map. 

That said, I'm happy to have your change. It's reasonable and will make sure that the code is clear about being thread safe while playing nicely with race detection.

I'm sorry to hear that issue resulted in production panics, but I think the approach you've taken in #231 is the right way to go about this.

**Comment by krzysztofdrys** [comment]
Thanks for your reply.

I added tests to my PR, so I think it is ready for the review.
