### ISSUE TITLE
Planner doesn't pass TypeProvider to evalIdent

### ISSUE THREAD

**Issue by joa** [cel-expr/cel-go#245]
**Describe the bug**
planner.go doesn't pass the type provider to `evalIdent` https://github.com/google/cel-go/blob/v0.2.0/interpreter/planner.go#L195 causing a panic in https://github.com/google/cel-go/blob/v0.2.0/interpreter/planner.go#L621 when using a custom type provider and `NewInterpretable` instead of `NewUncheckedInterpretable`

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
Can invest time in extracting a reproducible code sample if this is considered an actual issue. 

**Expected behavior**
Provider is used to resolve the type instead of a panic.

**Comment by TristonianJones** [comment]
Hi Joa,

Thanks for filing this bug. The missing provider is an oversight. While PR #223 should fix the issue, it still needs a bit more work and time, and there are faster ways to get you unblocked. There have been enough bug fixes since v0.2.0 that I'll put together a PR for this fix and cut a release. 

-Tristan

**Comment by joa** [comment]
Thank you @TristonianJones !
