### ISSUE TITLE
Default value with logical not in map type

### ISSUE THREAD

**Issue by davidebianchi** [cel-expr/cel-go#259]
**Describe the bug**
I don't know if is a bug or it is the expected behaviour. 
When I evaluate an expression with a logical not, declare a map of string and bool and access to an unknown value my expected value was the zero value, so the false value. Instead this returns a null value. 
The real problem was the evaluation of the logical not, that returns the null value.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Sample expression and input that reproduces the issue:
https://play.golang.org/p/an-p2QdGUpB
```cel
package main

import (
	"fmt"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/checker/decls"
)

func main() {
	env, _ := cel.NewEnv(
		cel.Declarations(
			decls.NewIdent("maps", decls.NewMapType(decls.String, decls.Bool), nil),
		),
	)
	parsed, _ := env.Parse("!maps.somekey")
	prg, _ := env.Program(parsed)

	out, _, _ := prg.Eval(map[string]interface{}{
		"maps": map[string]bool{"foo": true},
	})

	fmt.Printf("OUTPUT %v", out)
}
```

**Expected behavior**
I expect out to be true

**Additional context**

**Comment by TristonianJones** [comment]
Hi David,

Per the language spec section on [field selection](https://github.com/google/cel-spec/blob/master/doc/langdef.md#field-selection), the access of an absent key is treated as an error. So what you're observing is expected behavior.

The reasons might not be obvious, but it's primarily for safety. In particular something that might seem harmless like `!maps.somekey` could actually end up translating into an inadvertent access grant. Here are some ways that CEL can makes this a bit less painful though:

1. The logical `&&`, `||` are commutative, so the following statement will yield `true`:
    * `!maps.somekey || maps.foo`

2. Key presence is testable within maps using either the `has` macro or the `in` operator, so the following statement would yield `false`:
    * `'somekey' in maps && !maps.somekey` 
    * `!has(maps.somekey)`

Depending your use case, the recommended practice is to handle the error after evaluation as `false` by default (fail closed), or `true` by default (fail open), so that when you get an error you can tell your users (or yourself) what the behavior will be. 

Another option is to add a `getOrDefault` style helper on the `map` which tests key presence and converts to the default value on absence.

```go
package main

import (
	"fmt"

	"github.com/google/cel-go/cel"
	"github.com/google/cel-go/checker/decls"
	"github.com/google/cel-go/common/types"
	"github.com/google/cel-go/common/types/ref"
	"github.com/google/cel-go/common/types/traits"
	"github.com/google/cel-go/interpreter/functions"
)

func main() {
	// Build up the type declarations for type params and a map<A, B> type.
	paramA := decls.NewTypeParamType("A")
	paramB := decls.NewTypeParamType("B")
	typeParamABList := []string{"A", "B"}
	mapOfAB := decls.NewMapType(paramA, paramB)
	env, _ := cel.NewEnv(
		// Note, declarations are only necessary for checked expressions.
		cel.Declarations(
			// Maps variable.
			decls.NewIdent("maps", decls.NewMapType(decls.String, decls.Bool), nil),
			// Declare the map.get(<key>, <value>) function
			decls.NewFunction("get",
				decls.NewParameterizedInstanceOverload(
					// overload id
					"map_get_or_default",
					// arguments: map type, key value type, default value
					[]*exprpb.Type{mapOfAB, paramA, paramB},
					// return type: value type
					paramB,
					// type param names
					typeParamABList),
			),
		),
	)

	parsed, _ := env.Parse("!maps.get('somekey', false)")
	checked, _ := env.Check(parsed)
	prg, _ := env.Program(checked,
		// Implement the function, making sure to check argument types.
		cel.Functions(
			&functions.Overload{
				Operator: "get",
				Function: func(values ...ref.Val) ref.Val {
					// Ensure there are only three arguments
					if len(values) != 3 {
						return types.NewErr("no such overload")
					}
					// Try to convert to a map type. 
					m, isMap := values[0].(traits.Mapper)
					if !isMap {
						return types.ValOrErr(values[0], "first argument must be a map")
					}
					k := values[1]
					def := values[2]
					if v, found := m.Find(k); found {
						return v
					}
					return def
				},
			},
		),
	)

	out, _, _ := prg.Eval(map[string]interface{}{
		"maps": map[string]bool{"foo": true},
	})
	fmt.Printf("OUTPUT %v\n", out)
}
``` 

Hopefully that helps clarify some of the inner workings of CEL. Obviously extending CEL isn't necessarily pretty (hopefully we'll make that look better), but you can assign the functional options and environment ahead of time and use it over and over again. If you have any other questions you're also welcome to reach out to cel-go-discuss@googlegroups.com.
