### ISSUE TITLE
ResidualAst breaks on known selectors

### ISSUE THREAD

**Issue by tmthrgd** [cel-expr/cel-go#383]
**Describe the bug**
`ResidualAst` and `interpreter.PruneAst` don't work correctly when they encounter a selector that it's able to prune. Instead of substituting the entire selector for the constant value, it only substitutes the left-most part, leaving the field selector behind.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [x]  interpreter

Test setup:
```go
func Test_ResidualAst_Select(t *testing.T) {
	e, _ := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("x", decls.NewMapType(decls.String, decls.Int)),
			decls.NewVar("y", decls.Int),
		),
	)
	ast, _ := e.Parse("x.abc == y")
	prg, _ := e.Program(ast,
		cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval),
	)
	vars, _ := cel.PartialVars(map[string]interface{}{
		"x": map[string]interface{}{"abc": 123},
	}, cel.AttributePattern("y"))
	out, det, err := prg.Eval(vars)
	if !types.IsUnknown(out) {
		t.Fatalf("got %v, expected unknown", out)
	}
	if err != nil {
		t.Fatal(err)
	}
	residual, err := e.ResidualAst(ast, det)
	if err != nil {
		t.Fatal(err)
	}
	expr, err := cel.AstToString(residual)
	if err != nil {
		t.Fatal(err)
	}
	if expr != "123 == y" {
		t.Errorf("got expr: %s, wanted 123 == y", expr)
	}
}
```

**Expected behavior**
This should evaluate the `x.abc` to a constant `123` to be compared to the missing `y`, but instead it produces the garbage `123.abc == y`.

```
=== RUN   Test_ResidualAst_Select
    filter_test.go:87: got expr: 123.abc == y, wanted 123 == y
--- FAIL: Test_ResidualAst_Select (0.00s)
```

**Additional context**
I'm very new to this library, but I believe the problem lies with `interpreter.PruneAst`. In particular perhaps the `*exprpb.Expr_SelectExpr` case in `(*astPruner).prune`. I haven't tried any of the other special cases like calls, lists, etc. so I can't say whether they work correctly or not.

---

**Edit:** As a workaround, select and index expressions can be wrapped in no-op type conversions like `int(x.abc) == y` and they will resolve properly.

**Comment by TristonianJones** [comment]
Thanks for the detailed report! This is either an issue with the `PruneAst` or the numeric IDs associated with an `Attribute`. I'll take a look first thing tomorrow

**Comment by tmthrgd** [comment]
@TristonianJones You're dead right about the numeric IDs.

The initial problem is that the various quantifiable attributes (`absoluteAttribute`, `conditionalAttribute`, `maybeAttribute` and `relativeAttribute`) use the unqualified ID and not a more specific ID and `planSelect` defers to them for the ID. So when `evalWatchAttr` calls `state.SetValue` (through `observer`), it's using the ID of `x` rather than of `x.abc`.

That seems to be fixed if I add a `a.id = qual.ID()` to each of the `AddQualifier` methods on those types, though I have no idea whether that is the right fix or not. I'm also not sure if their `Qualify` methods might be broken as well or not as they use the same ID for the qualifiers.

However I've found the same bug with index expressions, and I'm not quite sure how they should be fixed. I'm guessing that `planCallIndex` should persist `expr.ID` through to the returned `Interpretable` somehow. Perhaps the proper fix is for both `planSelect` and `planCallIndex` to properly persist the `expr.ID` by wrapping whatever they would be returning.

I'm really not sure what the correct fix is so I'll leave it up to you, but hopefully all of that helps you with a fix.

Here's an expanded test case with a few more variants of this bug:

```go
func Test_ResidualAst_AttributeQualifiers(t *testing.T) {
	e, _ := cel.NewEnv(
		cel.Declarations(
			decls.NewVar("x", decls.NewMapType(decls.String, decls.Dyn)),
			decls.NewVar("y", decls.NewListType(decls.Int)),
			decls.NewVar("u", decls.Int),
		),
	)
	ast, _ := e.Parse(`x.abc == u && x["abc"] == u && x[x.string] == u && y[0] == u && y[x.zero] == u && (true ? x : y).abc == u && (false ? y : x).abc == u`)
	prg, _ := e.Program(ast,
		cel.EvalOptions(cel.OptTrackState, cel.OptPartialEval),
	)
	vars, _ := cel.PartialVars(map[string]interface{}{
		"x": map[string]interface{}{
			"zero":   0,
			"abc":    123,
			"string": "abc",
		},
		"y": []int{123},
	}, cel.AttributePattern("u"))
	out, det, err := prg.Eval(vars)
	if !types.IsUnknown(out) {
		t.Fatalf("got %v, expected unknown", out)
	}
	if err != nil {
		t.Fatal(err)
	}
	residual, err := e.ResidualAst(ast, det)
	if err != nil {
		t.Fatal(err)
	}
	expr, err := cel.AstToString(residual)
	if err != nil {
		t.Fatal(err)
	}
	const want = "123 == u && 123 == u && 123 == u && 123 == u && 123 == u && 123 == u && 123 == u"
	if expr != want {
		t.Errorf("got expr: %s, wanted %s", expr, want)
	}
}
```

```
=== RUN   Test_ResidualAst_AttributeQualifiers
    filter_test.go:94: got expr: 123.abc == u && 123["abc"] == u && 123[x.string] == u && 123[0] == u && 123[x.zero] == u && 123.abc == u && 123.abc == u, wanted 123 == u && 123 == u && 123 == u && 123 == u && 123 == u && 123 == u && 123 == u
--- FAIL: Test_ResidualAst_AttributeQualifiers (0.00s)
```

**Comment by TristonianJones** [comment]
Perfect, thank you for all of the added detail. 

The introduction of `Attribute` values was a pretty substantial change for how CEL programs are evaluated, but they enabled much better performance and the more flexible options for partial evaluation. The one thing that both @JimLarson and I had discussed at the time was the potential impact on the state tracking, where at best the state tracked would be more sparse, and at worst it might have an impact on the correctness of the residual. Given all of the added detail here, we now know for sure that the use of the variable node for the `Attribute` rather than the last qualifier was incorrect.

I think the fix is probably pretty straight-forward, but I'll have to double check it's behavior in all cases.

**Comment by TristonianJones** [comment]
I have a candidate fix which tracks all states of `Attribute` resolution from the first variable to the last variable qualification. Additionally, I've created a simple abstraction for recording the result of an index call into the call id (rather than the top-level variable id), but it needs further testing for how it might interact with partial evaluation with index expressions. I should get to the additional tests and the general cleanup of the `PruneAst` method (#384) tomorrow.

Thank you again for the high-quality bug reports and repro cases.
