### ISSUE TITLE
protobuf: update deprecated github.com/golang/protobuf/proto to google.golang.org/protobuf/proto

### ISSUE THREAD

**Issue by lopezator** [cel-expr/cel-go#385]
We are using [golangci-lint](https://github.com/golangci/golangci-lint) with several linters in our project to spot bugs. One of them is complaining with tjhe following message:

> SA1019: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)

As we are using this in some part of our project:

```
typeProvider := types.NewRegistry(mymessage)
```

I found myself in the situation where I cannot update my own code to `google.golang.org/protobuf/proto`, because the above line would complain about expecting `github.com/golang/protobuf/proto` not `google.golang.org/protobuf/proto`.

P.D. I would recommend using golangci-lint also here, I made a run over the project and found several apparently unused things, deprecations, etc.

**Comment by TristonianJones** [comment]
Hi @lopezator, good to hear from you. I haven't made this upgrade yet because it's not quite as simple as switching over since the old and new libraries treat proto reflection quite differently and there's a decent chunk of code in CEL dedicated to papering over the differences. I'll need to support both the legacy and the new style for quite some time.

I will take this as a feature request to support the google.golang.org/protobuf/proto library though.

Thanks for the tip on the golangci-lint. I'll give it a try.

**Comment by lopezator** [comment]
Thank you @TristonianJones for your fast response and your job with cel-go. This is moving fast 😊. 

I didn't want to make it seem like this was something trivial to change. I don't explain myself well in English sometimes, sorry for that.

By the way, I'm on the golangci-lint maintainers team, so if you decide to try it out, I'd be happy to help in the case you need something.

**Comment by TristonianJones** [comment]
No need for apologies @lopezator, I mostly wanted to communicate my regrets that it may take some time for me to implement the change. I hope this isn't holding you up too much. I really appreciate your patience, your advice, and your detailed reports.

**Comment by autom8ter** [comment]
Any idea how long this will take to implement?

**Comment by TristonianJones** [comment]
See pull #399. It's out for review now.
