### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ns-arulsmv** [cel-expr/cel-go#403]
https://codelabs.developers.google.com/codelabs/cel-go/index.html#6

claims needed to be copied from the previous example

**Comment by TristonianJones** [comment]
@ns-arulsmv I'm not seeing an error specifically, the claims object is being built dynamically. Could you add some more detail?

**Comment by TristonianJones** [comment]
The `claims` value is intentionally omitted to showcase how commutative logical operators work in CEL.

**Comment by ns-arulsmv** [comment]
I understand the purpose, can you work out the second (or the last in that page) example? Does it give compile error or execute as it is?

Without waiting for the response why did you close the ticket. Should I create another ticket?

**Comment by TristonianJones** [comment]
I closed the ticket since I thought the comment was about the expected input for the CEL expression. If that wasn't the case, then more details would be helpful in triaging the report. If you encounter an error, please paste it in the issue as this removes a large portion of the guess work and helps us better understand what you'd like to see changed.

**Comment by ns-arulsmv** [comment]
Thank you, in exercise3 last example leads a compile error 
Code copypasted from the last section (intentionally omitting line number for the blow error) . it would be some where near 154. or the line is

eval(program, request(auth("user:me@acme.co"), time.Now()))

codelab/codelab.go:XXX:29: not enough arguments in call to auth
	have (string)
	want (string, map[string]string)

**Comment by TristonianJones** [comment]
Fixed in the latest codelab push.
