### ISSUE TITLE
Null comparisons only with null

### ISSUE THREAD

**Issue by bigkevmcd** [cel-expr/cel-go#415]
**Describe the bug**
It's not uncommon to receive a `null` value in a JSON document.

Currently, you can't make any meaningful check for a value being null.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:

With the JSON document:

```json
{
  "value": "testing",
  "missing": null
}
```
 * `body.value == null` fails with a `no such overload`
 * `body.missing == null` returns true

Test setup:
```go
// These are currently erroring out with overload errors.
func TestNullEquality(t *testing.T) {
	if NullValue.Equal(String("hello")).(Bool) {
		t.Error("Comparing Null with a String succeeded")
	}
	if String("hello").Equal(NullValue).(Bool) {
		t.Error("Comparing String with a Null succeeded")
	}
	if IntZero.Equal(NullValue).(Bool) {
		t.Error("Comparing Int with a Null succeeded")
	}
}
```

**Expected behavior**
Non-Null values should be comparable (unsuccessfully) to Null.

**Additional context**

https://github.com/tektoncd/triggers/issues/952

This unfortunately affects most types/values, so rather than adding explicit comparison checks, I wonder if there's a better way?

**Comment by TristonianJones** [comment]
@bigkevmcd Thanks for filing the ticket. This is unfortunately a side-effect of only supporting homogeneous equality. Many programming languages support heterogeneous equality and this is something that we eventually intend to support, but has been tricky to approach mostly because of the presence of JSON `number` values. 

As a workaround might I suggest `type(body.value) == null_type` as this will at least indicate whether the value is `null` without causing problems.

**Comment by TristonianJones** [comment]
I haven't forgotten about this, and am working on a proposal to improve the ease of use of `null`.

**Comment by TristonianJones** [comment]
It was just decided today that CEL will support heterogeneous equality. The approved proposals will be documented in cel-spec.

**Comment by bigkevmcd** [comment]
@TristonianJones That's great, thank you for the update.
