### ISSUE TITLE
Map Concatenation

### ISSUE THREAD

**Issue by jarreds** [cel-expr/cel-go#454]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [ ] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
The ability concatenate two `map` values with RHS keys taking precedence.

**Example**
`{"a": "0", "c": "3"} + {"a": "1, "b": "2"} == {"a": "1", "b": "2", "c": "3"}`

**Alternatives considered**
We can currently nest `map` objects to construct new "combined" instances. Eg `{"old": someMap, "newKey": "newValue"}`. The ability to do this in a non-nested fashion is desirable.

The JS spread operator is another potential source of inspiration `{...someMap, "newKey": "newValue"}`

**Comment by TristonianJones** [comment]
The most likely thing we will do is add extensions to `merge` maps. There are a few different merge methods that people request: 
* add new or overwrite duplicate keys
* overwrite only duplicates
* add only new
* add new or merge duplicate key-values

In part we haven't added anything here because usually only one of those approaches is needed and users can pick what they want and expose a custom function to do it. We won't provide operater overloads or syntactic changes here though as the semantics are not completely obvious for what should happen in all cases.

**Comment by jarreds** [comment]
The merge extensions approach makes total sense. Thank you for your thoughtful consideration.
