### ISSUE TITLE
Language design philosophy

### ISSUE THREAD

**Issue by tamalsaha** [cel-expr/cel-go#50]
I am trying to get familiar with cel lang in the context of opa project. Since I can't open issues against the cel-spec, I am filing it here. I am no language designer. From the readme I see that 

`
CEL is a non-Turing complete language designed to be portable and fast. It is best suited to applications where sandboxing a full-fledged language like JavaScript or Lua would be too resource intensive, but side-effect free dynamic computations are strongly desired.
`

I am curious to understand why the following 2 are desired properties:

- non-Turing complete language
- side-effect free dynamic computations 

Thanks.

**Comment by TristonianJones** [comment]
Hi Tamal,

Good questions.

Non-Turing complete language means that evaluation is guaranteed to complete. This does not mean that the expression cannot be expensive, but it does mean it will never loop forever.

Side-effect free computation means the same inputs will always yield the same outputs. The expression (and its evaluation) is stateless. If you were to introduce side-effects into the language this would mean that partial state evaluation wouldn't be safe, and often this is desired for security efforts where many different pieces of information need to be combined from a series of sources in order to produce a consistent result (e.g. allow / deny).

Hopefully that answers your questions!

-Tristan
