### ISSUE TITLE
Confusing example - how is common.Errors used and why is it passed around?

### ISSUE THREAD

**Issue by broady** [cel-expr/cel-go#55]
The example in the readme...

```
// Parse the expression and returns the accumulated errors.
p, errors := parser.ParseText("a || b && c.exists(x, x > 2)")
if len(errors.GetErrors()) != 0 {
    return nil, fmt.Error(errors.ToDisplayString()))
}

// ...
env := checker.NewStandardEnv(packages.DefaultPackage, typeProvider, errors)
// ...
if len(errors.GetErrors()) != 0 {
    return nil, fmt.Error(errors.ToDisplayString()))
}
```

This is quite confusing - why is the `errors` struct being passed around? What's the reason for returning it from the parser and passing it into the environment?

From my reading, the checker env isn't re-usable or goroutine-safe.

As a newcomer to the package, I'd expect a flow like:

* create environment, provide type information, etc.
* parse and check the expression against the environment
* evaluate the expression

The current interface seems to entangle these operations.

**Comment by TristonianJones** [comment]
The example in the `README.md` expects that users are always parsing and type-checking before evaluating, and `errors` are accumulated between the `parser` and `checker`. I mostly wanted to indicate that one depends on the other, but there are probably better ways to structure this. 

Would you prefer the `checker` return its own instance of `errors` rather than accumulate? I think this addresses your re-use / goroutine safety concerns.
