### ISSUE TITLE
How to validate the array of self-defination struct?

### ISSUE THREAD

**Issue by spencersong123** [cel-expr/cel-go#607]
I have a self-defination struct like this
```go
type student {
    name string
    age int
}
```
then, I generate a array of "student"
```go
students := make([]*student, 0)
students = append(students, &student{"123",18}),
students = append(students, &student{"456",19}),
students = append(students, &student{"789",20}),
```
if the age of all the students is more than 17,it returns true,otherwise,returns false
What should I do?

**Comment by TristonianJones** [comment]
Is the type definition intended to be representative of Golang or proto? If it's go, then the fields would need to be exported (e.g. UpperCamelCase) and you'd need to use the upcoming `ext.NativeTypes()` option introduced in #612 in order to be able to access instances of the type.

Expression-wise, the type names for Go structs are the simple package name followed by the exported type name. The following type would be exposed as `edu.Student`:

```
package edu;

type Student struct {
   Name string
   Age int
}
```

To evaluate over `edu.Student` instances, you would need to configure your CEL environment as follows:

```go
env, _ := cel.NewEnv(
    ext.NativeTypes(reflect.TypeOf(&edu.Student{})),
    cel.Variable("students", cel.ListType(cel.ObjectType("edu.Student"))),
)

ast, iss := env.Compile(`students.all(student, student.Age > 17)`)
prg, err := env.Program(ast)
out, _, err := prg.Eval(cel.NoVars()) // out is equal to types.True or types.False
return out, err
```
