### ISSUE TITLE
OneOf Handling

### ISSUE THREAD

**Issue by jacobmikesell** [cel-expr/cel-go#786]
**Describe the bug**
Today cel-go does not appear to handle oneofs in protobuf correctly, it treats all unpopulated one ofs as having their Zero type populated instead of at most one value being populated.

**To Reproduce**
Check which components this affects:

- [x]  interpreter

Sample expression and input that reproduces the issue:
```proto
TestMessage{
oneof field {
string foo = 1;
string bar = 2;
}
}
```

```cel
bar == ''
```

Test setup:
```go
        env, err := NewEnv(&testproto.TestMessage{})
	require.NoError(t, err)
	ast, issues := env.Compile("bar == ''")
	require.NoError(t, issues.Err())
	program, err := env.Program(ast)
        require.NoError(t, err)

	vars, err := cel.ContextProtoVars(&testproto.TestMessage{
		field: &testproto.TestMessage_Foo{Foo: "abc"},
	})
	require.NoError(t, err)
	eval, _, err := program.Eval(vars)
	require.NoError(t, err)
	assert.Equal(t, types.Bool(false), eval)
```

**Expected behavior**
I would expect this to be false, as the message can never have any value for bar. this feels even more problematic when the one of values are message types as indexing into the message for values can evaluate to true.

**Additional context**

**Comment by TristonianJones** [comment]
@jacobmikesell this is a limitation of context protos in that the top level fields are all treated as variables, even within oneof values, so it's practically impossible to tell which one is set and still ensure that all possible variables are defined at runtime. Not publishing a variable in this case would be a runtime error rather than a boolean result.

This is working as intended, and working like field accesses work for oneofs outside the context case. The only difference is you can't test which oneof case was set.

I realize it's a bit confusing, but the feature is really intended to be a simplification for some users who manage a lot of variables in a common location outside CEL.

**Comment by jacobmikesell** [comment]
@TristonianJones Thanks for the quick response!
