### ISSUE TITLE
Possible regression in type handling

### ISSUE THREAD

**Issue by jpbetz** [cel-expr/cel-go#816]
In CEL 1.16,

```cel
dyn([]).sum() == 0
```

This was always true

but in CEL 1.17, this sometimes returns false.  It appears that this may be related to what type `dyn([])` is assigned.  If I run `dyn([]).sum()` it most often returns an int, but sometimes returns a uint or duration.

See https://github.com/kubernetes/kubernetes/blob/8a8d63a732dea705fd38fab7d79e3730642bb2f7/staging/src/k8s.io/apiserver/pkg/cel/library/lists.go#L139 for the `sum()` implementation.

**Comment by jpbetz** [comment]
cc @TristonianJones

**Comment by TristonianJones** [comment]
@jpbetz Are you certain this issue isn't present in v0.16.*? The problem is that while overloads were given a stable ordering during type-checking, apparently I missed a place where overload resolution via dynamic dispatch was still using the map (hence the randomness) rather than the ordered list of overloads as they were configured by the user

https://github.com/google/cel-go/blob/6548b404d5060761fee39c7492c6fb0fa2048690/cel/decls.go#L668-L670

**Comment by jpbetz** [comment]
I'm not certain about `v0.16.*`, but the test for this started failing at a low rate (1 of 5 or so) when I bumped to `v0.17.*.`

**Comment by TristonianJones** [comment]
I'll patch the update in #817 to v0.16.2 as well. I think it's a problem for both releases.

**Comment by jpbetz** [comment]
Thank you!

**Comment by TristonianJones** [comment]
I must have been looking in the wrong place, v0.16 is not affected, just v0.17+ I'm going to create a point release for v0.17.2 based on this.

**Comment by jpbetz** [comment]
That's a relief!  Thanks for the back port!
