### ISSUE TITLE
Testing timestamppb fields against null

### ISSUE THREAD

**Issue by mkatri** [cel-expr/cel-go#869]
**Describe the bug**
`google.protobuf.Timestamp` fields in protobuf messages can be `null`.
CEL parser compiles `msg.timestamp_field == null` as expected, but the expression always evaluates to `false`.
This is because [timestamppb](https://pkg.go.dev/google.golang.org/protobuf/types/known/timestamppb) is considered a `decls.Timestamp`

This behavior is inconsistent with other protobuf types.
For example `google.protobuf.StringValue` fields are `decls.NewWrapperType(decls.String)`
And the expression `msg.string_value_field == null` does not always evaluate to false.

**To Reproduce**
Check which components this affects:

- [ ]  parser
- [ ]  checker
- [X]  interpreter

Sample expression and input that reproduces the issue:
```cel
msg.timestamp_field == null
```

Test setup:
```protobuf
message TestMessage {
  google.protobuf.Timestamp timestamp_field = 1;
  google.protobuf.StringValue string_field = 2;
}
```

```go
env, _ := cel.NewEnv(decls.NewVar("msg", decls.NewObjectType("TestMessage")))
ast, _ := env.Compile("msg.string_field == null && msg.timestamp_field == null")
prg, _ := env.Program(ast)
out, _, err := prg.Eval(map[string]interface{}{
    "msg":   &TestMessage{},
})
fmt.Println(out)
```

**Expected behavior**
Program should output `True`

**Comment by TristonianJones** [comment]
Rather than test against `null`, prefer using the `has()` macro which is designed to handle the complex matrix of behaviors that can occur with presence testing between proto2 and proto3 message types. Field accesses of a protobuf message are intended to produce the default value for the field type upon access.

```
has(msg.string_field) && has(msg.timestamp_field)
```

The value `null` only really exists to support the concrete JSON `null` which was introduced into the CEL spec by way of `google.protobuf.Value` support which treats a `null` as a special sentinel value. Wrapper types also support `null`; however, the design was intended to reflect the code generation behavior of protobuf clients. In retrospect, we would have preferred not to support wrapper types as a special case.
